-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Country"
(
    "ID" integer NOT NULL,
    name character varying NOT NULL,
    iso_code character varying NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Agricultural_Census"
(
    "ID" integer NOT NULL,
    census_year integer NOT NULL,
    decade character varying NOT NULL,
    "Country_ID" integer NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Rural_Property_Distributuon"
(
    "ID" integer NOT NULL,
    total_area_ha real NOT NULL,
    number_of_properties integer NOT NULL,
    "Size_Range_ID" integer NOT NULL,
    "Agricultural_Census_ID" integer NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Farm_Size_Range"
(
    "ID" integer NOT NULL,
    lower_limit integer NOT NULL,
    upper_limit integer NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Agricultural_Production"
(
    "ID" integer NOT NULL,
    year integer NOT NULL,
    production_tons real NOT NULL,
    "Product_ID" integer NOT NULL,
    "Country_ID" integer NOT NULL,
    number_of_animals integer,
    harvested_area_ha real,
    PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Agricultural_Product"
(
    "ID" integer NOT NULL,
    name character varying NOT NULL,
    type character varying NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Food_Security_Measurement"
(
    "ID" integer NOT NULL,
    year integer NOT NULL,
    value real NOT NULL,
    "Country_ID" integer NOT NULL,
    "Indicator_ID" integer NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Food_Security_Indicator"
(
    "ID" integer NOT NULL,
    name character varying NOT NULL,
    unit character varying NOT NULL,
    PRIMARY KEY ("ID")
);

ALTER TABLE IF EXISTS public."Agricultural_Census"
    ADD FOREIGN KEY ("Country_ID")
    REFERENCES public."Country" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Rural_Property_Distributuon"
    ADD FOREIGN KEY ("Agricultural_Census_ID")
    REFERENCES public."Agricultural_Census" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Rural_Property_Distributuon"
    ADD FOREIGN KEY ("Size_Range_ID")
    REFERENCES public."Farm_Size_Range" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Agricultural_Production"
    ADD FOREIGN KEY ("Country_ID")
    REFERENCES public."Country" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Agricultural_Production"
    ADD FOREIGN KEY ("Product_ID")
    REFERENCES public."Agricultural_Product" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Food_Security_Measurement"
    ADD FOREIGN KEY ("Country_ID")
    REFERENCES public."Country" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Food_Security_Measurement"
    ADD FOREIGN KEY ("Indicator_ID")
    REFERENCES public."Food_Security_Indicator" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;